### ISSUE TITLE
Spellblade Aluriel (The Nighthold) spellid

### ISSUE THREAD

**Issue by Xerus2** [BigWigsMods/BigWigs_Legion#5]
1x Found spell 'Searing Brand' using id 213148 on 15, tell the authors!
BigWigs_Core\BossPrototype.lua:1141: in function `UnitDebuff'
BigWigs_Legion\Nighthold\Aluriel.lua:417: in function `?'
BigWigs_Core\BossPrototype.lua:456: in function <BigWigs_Core\BossPrototype.lua:422>

Locals:
InCombatSkipped

**Comment by Zireael-N** [comment]
Does this happen on difficulties other than Heroic?

**Comment by Xerus2** [comment]
Yes:

1x Found spell 'Searing Brand' using id 213148 on 14, tell the authors!
[string "@BigWigs_Core\BossPrototype.lua"]:1168: in function `UnitDebuff'
[string "@BigWigs_Legion\Nighthold\Aluriel.lua"]:417: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:474: in function <BigWigs_Core\BossPrototype.lua:440>

Locals:
Skipped (In Encounter)

**Comment by Xerus2** [comment]
And on all difficulties, I waited the entire time until she cast Searing Brand on me before I killed her, so I don't know why the Heroic/Mythic behavior would be different, unless something has changed behind the scenes since I opened this ticket originally.

**Comment by Zireael-N** [comment]
Thanks for checking.

I looked into it, the error would occur if you had both https://www.wowhead.com/spell=213148/searing-brand and https://www.wowhead.com/spell=213166/searing-brand at the same time. Also BigWigs remembers spells it complained about in the current session, so if you tried all difficulties without logging out, that could be another reason you only got 1 error.

**Comment by Xerus2** [comment]
Ah, makes sense. Yes, I didn't log out between difficulty checks. Thanks for fixing!
